const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
const POST_ACTIVITY = "POST_ACTIVITY";
const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
const GET_BY_NAME = "GET_BY_NAME";
const FILTER_BY_CONTINENTS = "FILTER_BY_CONTINENTS";
const FILTER_BY_ACTIVITIES = "FILTER_BY_ACTIVITIES";
const ORDER_ASC_DSC = "ORDER_ASC_DSC";
const ORDER_BY_POP = "ORDER_BY_POP";

export {
  GET_COUNTRIES,
  GET_COUNTRY_BY_ID,
  POST_ACTIVITY,
  GET_ALL_ACTIVITIES,
  GET_BY_NAME,
  FILTER_BY_CONTINENTS,
  FILTER_BY_ACTIVITIES,
  ORDER_ASC_DSC,
  ORDER_BY_POP,
};
