const GET_COUNTRIES = "GET_COUNTRIES";
const GET_COUNTRY_BY_ID = "GET_COUNTRY_BY_ID";
const POST_ACTIVITY = "POST_ACTIVITY";
const GET_ALL_ACTIVITIES = "GET_ALL_ACTIVITIES";
const FILTER_BY_NAME = "FILTER_BY_NAME";
const FAILURE = "FAILURE";

export {
  GET_COUNTRIES,
  GET_COUNTRY_BY_ID,
  POST_ACTIVITY,
  GET_ALL_ACTIVITIES,
  FILTER_BY_NAME,
  FAILURE,
};
