const DIFFICULT = ["No difficulty", "1", "2", "3", "4", "5"];
const DURATION = [
  "No fixed duration",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
];
const SEASON = ["No season", "Spring", "Summer", "Autumn", "Winter"];

// ------------------------------------------------------------------------------------------------------

const BY_CONTINENTS = [
  "All Continents",
  "Africa",
  "Antartica",
  "Asia",
  "Europe",
  "Central America",
  "North America",
  "South America",
  "Oceania",
];
const BY_ACTIVITY = [
  "Boat Racing",
  "Car Racing",
  "Extreme Surf",
  "Hiking",
  "Jogging",
  "Kayaking",
  "Racing Cars",
  "Sailing",
  "Yachting Navigate",
];

// Solo para testeo...
const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Argelia",
  "Argentina",
  "Australia",
  "Austria",
  "Bahamas",
  "Belarus",
  "Belgium",
  "Bolivia",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chile",
  "China",
  "Colombia",
  "Ecuador",
  "El Salvador",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Iraq",
  "Israel",
  "Italia",
  "Jamaica",
  "Japan",
  "Madagascar",
  "Mexico",
  "Peru",
  "United States",
  "Venezuela",
  "Zambia",
];

export { DIFFICULT, DURATION, SEASON, BY_CONTINENTS, BY_ACTIVITY, COUNTRIES };
